#spring.application.name=user-services
#spring.data.mongodb.uri=mongodb+srv://ihannan808_db_user:N2r5dllYVbxmQqgQ@users-ecom.kg6vwsm.mongodb.net/?appName=users-ecom
#spring.data.mongodb.database=userdb
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.data.mongodb.core=DEBUG
#logging.level.org.springframework.data.mongodb.repository=DEBUG
#logging.level.org.springframework.boot.autoconfigure=INFO
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.mongodb.driver=DEBUG
#server.port=8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-db
      database: user-db
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: jdbc:h2:mem:test
  #  jpa:
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: create

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb?options=-c%20TimeZone=Asia/Kolkata
#    #this is nothing but POSTGRES_USER: hannan from docker compose.yml
#    username: hannan
#    password: hannan
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    properties:
#      hibernate.jdbc.time_zone: Asia/Kolkata
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost