spring:
  application:
    name: product-service
  datasource:
    #url: jdbc:postgresql://ep-shy-night-a4xc0tsj-pooler.us-east-1.aws.neon.tech/product
    #url: jdbc:mysql://localhost:3306/productservice
    url: jdbc:postgresql://localhost:5432/product?options=-c%20TimeZone=Asia/Kolkata
    username: hannan
    password: hannan
    #this is nothing but POSTGRES_USER: hannan from docker compose.yml
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
      formal_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true